package prism.infrastructure.filesystem;

import org.jspecify.annotations.NonNull;
import prism.configuration.context.AbstractServiceContextConfiguration;
import prism.domain.model.Prism;

import java.util.function.Supplier;

public class FileColorWriter {

    private static final String DO_NOT_CHANGE = """
            Warning: This file is automatically generated by Prism, and may be overwritten by it.
            Manual modifications may be lost or cause unexpected behavior. Do not edit or delete this file.
            """;

    private final Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext;

    public FileColorWriter(@NonNull Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext) {
        this.appExecutionContext = appExecutionContext;
    }

    public boolean writeSpectrum(@NonNull Prism prism) {
        return true;
    }
}