package prism.infrastructure.filesystem;

import org.jspecify.annotations.NonNull;
import prism.configuration.adapter.StorageAdapter;
import prism.configuration.adapter.WriterAdapter;
import prism.configuration.context.AbstractServiceContextConfiguration;
import prism.domain.model.Prism;
import prism.domain.model.Storage;
import prism.utils.FileUtils;
import tools.jackson.databind.ObjectMapper;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Iterator;
import java.util.function.Supplier;
import java.util.stream.Stream;

/**
 * Writes data structures such as {@link prism.domain.model.Storage} and {@link prism.domain.model.Prism} configurations
 * to their respective files on the filesystem.
 * <p>
 * This class utilizes the application's execution context to determine the proper
 * directories and file names for data persistence.
 */
public class FileDataWriter {

    private static final String DO_NOT_CHANGE = """
            # Warning: This file is automatically generated by Prism, and may be overwritten by it.
            # Manual modifications may be lost or cause unexpected behavior. Do not edit or delete this file.
            """;

    private final Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext;

    private final ObjectMapper mapper;

    /**
     * Constructs a new {@code FileDataWriter} with the given execution context supplier.
     *
     * @param appExecutionContext a supplier providing the current application context configuration
     */
    public FileDataWriter(@NonNull Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext) {
        this.appExecutionContext = appExecutionContext;

        this.mapper = new ObjectMapper();
    }

    /**
     * Serializes the given {@link prism.domain.model.Storage} instance to JSON and writes it to the
     * storage file defined in the application's configuration.
     *
     * @param storage the storage domain model to serialize and write
     * @throws IllegalStateException if the storage adapter configuration is missing
     * @throws RuntimeException      if an error occurs during file writing
     */
    public void writeStorage(@NonNull Storage storage) {
        String storageJson =
                mapper.writeValueAsString(storage);

        AbstractServiceContextConfiguration executionContext = this.appExecutionContext.get();
        StorageAdapter storageAdapter = executionContext.getStorageAdapter();

        if (storageAdapter == null) {
            throw new IllegalStateException("Storage configuration not present");
        }

        String dir = storageAdapter.getDirectory();
        String file = storageAdapter.getFile();
        Path storageFilePath = Path.of(FileUtils.buildPath(dir, file));

        FileUtils.assertFileAndDirExistence(storageFilePath);

        try (FileWriter writer = new FileWriter(storageFilePath.toString())) {
            writer.append(storageJson);
        } catch (Exception e) {
            throw new RuntimeException("Error while writing to storage file", e);
        }
    }

    /**
     * Writes the given {@link prism.domain.model.Prism} active configuration to the spectrum file defined in
     * the application's configuration.
     * <p>
     * If the target file already exists and its active configuration ID matches the given
     * prism's ID, the writing process is skipped. Otherwise, a temporary file is created,
     * populated with a warning header, the prism's ID, and its formatted content, and then
     * atomically moved to replace the target file.
     *
     * @param prism the prism domain model representing the active configuration to write
     * @throws IllegalStateException if the writer adapter configuration is missing
     * @throws RuntimeException      if an error occurs during validation or file writing
     */
    public void writeSpectrum(@NonNull Prism prism) {
        AbstractServiceContextConfiguration executionContext = this.appExecutionContext.get();
        WriterAdapter writerAdapter = executionContext.getWriterAdapter();

        if (writerAdapter == null) {
            throw new IllegalStateException(
                    "Writing configuration not present");
        }

        String dir = writerAdapter.getDirectory();
        String file = writerAdapter.getFile();

        Path path = Path.of(
                FileUtils.buildPath(dir, file));

        if (Files.exists(path)) {
            try (Stream<String> lines = Files.lines(path)) {
                Iterator<String> iterator = lines.iterator();

                while (iterator.hasNext()) {
                    String line = iterator.next();

                    if (line.startsWith("ID:")) {
                        if (line.equals(prism.getId())) {
                            return;
                        }
                        break;
                    }
                }
            } catch (Exception e) {
                throw new RuntimeException("Error while validating active configuration", e);
            }
        }

        FileUtils.assertFileAndDirExistence(path);

        try {
            Path temp = Files.createTempFile(
                    path.getParent(), "output-", ".tmp");

            try (BufferedWriter writer = Files.newBufferedWriter(temp)) {
                writer.write(DO_NOT_CHANGE);
                writer.newLine();

                writer.write(prism.getId());
                writer.newLine();

                writer.newLine();

                writer.write(prism.getFormatted());
            }

            Files.move(temp, path,
                    StandardCopyOption.ATOMIC_MOVE,
                    StandardCopyOption.REPLACE_EXISTING);

            Files.deleteIfExists(temp);
        } catch (Exception e) {
            throw new RuntimeException("Error while validating active configuration", e);
        }
    }
}