package prism.infrastructure.filesystem;

import org.jspecify.annotations.NonNull;
import prism.configuration.adapter.WriterAdapter;
import prism.configuration.context.AbstractServiceContextConfiguration;
import prism.domain.model.Prism;
import prism.utils.FileUtils;

import java.io.BufferedWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Iterator;
import java.util.function.Supplier;
import java.util.stream.Stream;

public class FileDataWriter {

    private static final String DO_NOT_CHANGE = """
            Warning: This file is automatically generated by Prism, and may be overwritten by it.
            Manual modifications may be lost or cause unexpected behavior. Do not edit or delete this file.
            """;

    private final Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext;

    public FileDataWriter(@NonNull Supplier<? extends AbstractServiceContextConfiguration> appExecutionContext) {
        this.appExecutionContext = appExecutionContext;
    }

    public void writeSpectrum(@NonNull Prism prism) {
        AbstractServiceContextConfiguration executionContext = this.appExecutionContext.get();
        WriterAdapter writerAdapter = executionContext.getWriterAdapter();

        if (writerAdapter == null) {
            throw new IllegalStateException(
                    "Writing configuration not present");
        }

        String dir = writerAdapter.getDirectory();
        String file = writerAdapter.getFile();

        Path path = Path.of(
                FileUtils.buildPath(dir, file));

        if (Files.exists(path)) {
            try (Stream<String> lines = Files.lines(path)) {
                Iterator<String> iterator = lines.iterator();

                while (iterator.hasNext()) {
                    String line = iterator.next();

                    if (line.startsWith("ID:")) {
                        return;
                    }
                }
            } catch (Exception e) {
                throw new RuntimeException("Error while validating active configuration", e);
            }
        }

        try {
            Path temp = Files.createTempFile(
                    path.getParent(), "output-", ".tmp");

            try (BufferedWriter writer = Files.newBufferedWriter(temp)) {
                writer.write(DO_NOT_CHANGE);
                writer.newLine();

                writer.write(prism.getId());
                writer.newLine();

                writer.write(prism.getFormatted());
            } finally {
                Files.deleteIfExists(temp);
            }

            Files.move(path, temp,
                    StandardCopyOption.ATOMIC_MOVE,
                    StandardCopyOption.REPLACE_EXISTING);
        } catch (Exception e) {
            throw new RuntimeException("Error while validating active configuration", e);
        }
    }
}