/*
 * This source file was generated by the Gradle 'init' task
 */
package shifter.ka;

import org.junit.jupiter.api.Test;

class DaemonTest {
    @Test void appHasAGreeting() {
        Daemon classUnderTest = new Daemon();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}