/*
 * This source file was generated by the Gradle 'init' task
 */
package prism;

import org.junit.jupiter.api.Test;

class DaemonOperationTest {
    @Test void appHasAGreeting() {
        AppOperation classUnderTest = new AppOperation();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}