/*
 * This source file was generated by the Gradle 'init' task
 */
package prism;

import org.junit.jupiter.api.Test;

class DaemonOperationTest {
    @Test void appHasAGreeting() {
        DaemonOperation classUnderTest = new DaemonOperation();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}